cargo-features = ["profile-rustflags", "edition2024"]
[package]
name = "Numcraft"
version = "0.1.0"
authors = ["NumWorks <contact@numworks.com>"]
edition = "2024"

[profile.dev]
panic="abort"
strip=true
opt-level= "z"
lto = true
codegen-units = 1

[profile.release]
panic="abort"
strip=true
opt-level= "z"
lto = true
codegen-units = 1

[profile.dev.package."renderer::fill_rect"]
opt-level = 3

[profile.release.package."renderer::fill_rect"]
opt-level = 3

[dependencies]
nalgebra = {version = "0.33.2", default-features = false, features = [ "libm" ]}
libm = "0.2.13"
format_no_std = "1.2.0"
heapless = "0.8.0"
cbitmap = "0.3.2"
cortex-m = {version="0.7.7", features=["critical-section-single-core"]}
embedded-alloc = "0.6.0"

[target.'cfg(any(windows, unix))'.dependencies]
minifb = "0.28"
rand = "0.9.1"
