cargo-features = ["profile-rustflags", "edition2024"]
[package]
name = "epsilon-sample-app"
version = "0.1.0"
authors = ["NumWorks <contact@numworks.com>"]
edition = "2024"

[profile.dev]
panic="abort"
strip=true
opt-level= "z"
lto = true
codegen-units = 1

[profile.release]
panic="abort"
strip=true
opt-level= "z"
lto = true
codegen-units = 1

[dependencies]
nalgebra = {version = "0.33.2", default-features = false, features = [ "libm" ]}
libm = "0.2.13"
emballoc = "0.3.0"
format_no_std = "1.2.0"
heapless = "0.8.0"
cbitmap = "0.3.2"

[target.'cfg(any(windows, unix))'.dependencies]
minifb = "0.28"
rand = "0.9.1"
