[package]
name = "epsilon-sample-app"
version = "0.1.0"
authors = ["NumWorks <contact@numworks.com>"]
edition = "2018"

[dependencies]
nalgebra = {version = "0.33.2", default-features = false, features = [ "libm" ]}
libm = "0.2.11"
alloc-cortex-m = "0.4.4"
