name: Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nwlink
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install -G nwlink
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: thumbv7em-none-eabihf
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
